# Generated by Django 4.1.3 on 2023-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
        ('dirby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dirby',
            options={'ordering': ('-date_created',), 'verbose_name': 'Dirbpy Target', 'verbose_name_plural': 'Dirbpy Targets'},
        ),
        migrations.RemoveField(
            model_name='dirby',
            name='data',
        ),
        migrations.AddField(
            model_name='dirby',
            name='scans',
            field=models.ManyToManyField(blank=True, to='scan.scan'),
        ),
    ]
