# Generated by Django 4.2 on 2023-10-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
        ('scanvus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanvus',
            options={'ordering': ('-date_created',), 'verbose_name': 'ScanVus Target', 'verbose_name_plural': 'Scanvus Targets'},
        ),
        migrations.RemoveField(
            model_name='scanvus',
            name='data',
        ),
        migrations.AddField(
            model_name='scanvus',
            name='scans',
            field=models.ManyToManyField(blank=True, to='scan.scan'),
        ),
    ]
