# Generated by Django 4.1.3 on 2023-08-21 02:50

from django.db import migrations, models
import helpers.random


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=helpers.random.random_uid, max_length=255, null=True)),
                ('meta', models.JSONField(default=dict, null=True)),
                ('status', models.CharField(choices=[('ST', 'Started'), ('RU', 'Running'), ('DO', 'Done'), ('FL', 'Failed')], default='ST', max_length=2)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'ordering': ('-created_at',),
            },
        ),
    ]
