# Generated by Django 4.2 on 2023-08-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no-username', max_length=255, null=True)),
                ('password', models.CharField(default='no-password', max_length=255, null=True)),
                ('auth', models.CharField(choices=[('BASIC', 'basic'), ('TOKEN', 'token'), ('NOAUTH', 'no-auth')], default='NOAUTH', max_length=255)),
                ('schema', models.CharField(choices=[('HTTPS', 'https://'), ('HTTP', 'http://'), ('SOCKS5', 'socks5://')], default='HTTP', max_length=255)),
                ('host', models.GenericIPAddressField(unique=True)),
                ('port', models.IntegerField(default=9201)),
                ('is_active', models.BooleanField(default=False)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
                'ordering': ('-created_at',),
            },
        ),
    ]
