# Generated by Django 4.2 on 2023-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyconfig',
            name='schema',
            field=models.CharField(choices=[('https://', 'Https'), ('http://', 'Http'), ('socks5://', 'Socks5')], default='http://', max_length=255),
        ),
    ]
