# Generated by Django 4.2 on 2023-08-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0002_alter_proxyconfig_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyconfig',
            name='protocol',
            field=models.CharField(choices=[('https', 'Https'), ('http', 'Http'), ('socks5', 'Socks5')], default='http', max_length=255),
        ),
        migrations.AlterField(
            model_name='proxyconfig',
            name='schema',
            field=models.CharField(choices=[('https', 'Https'), ('http', 'Http'), ('socks5', 'Socks5')], default='http', max_length=255),
        ),
    ]
